Repository openml/automlbenchmark, pull requests merged in 2020-04, with the labels that each got.

#86 Moving sklearn to v0.6.0
  frameworks/autosklearn/__init__.py
  frameworks/autosklearn/exec.py
  frameworks/autosklearn/requirements.txt
  frameworks/autosklearn/setup.sh
  frameworks/shared/callee.py
  resources/frameworks.yaml
Labels: framework

#88 Singularity support
  .gitignore
  amlb/__init__.py
  amlb/container.py
  amlb/docker.py
  amlb/resources.py
  amlb/singularity.py
  frameworks/AutoWEKA/__init__.py
  frameworks/GAMA/__init__.py
  frameworks/H2OAutoML/__init__.py
  frameworks/RandomForest/__init__.py
  frameworks/autosklearn/__init__.py
  frameworks/autoxgboost/__init__.py
  frameworks/hyperoptsklearn/__init__.py
  frameworks/oboe/__init__.py
  frameworks/ranger/__init__.py
  resources/config.yaml
  resources/frameworks.yaml
  runbenchmark.py
Labels: enhancement

#89 fixed docker running in aws (got broken after singularity support)
  amlb/aws.py
  amlb/container.py
  amlb/singularity.py
Labels: bug

#91 Issue 90: fix Singularity support
  amlb/singularity.py
Labels: bug

#95 Issue 84: upgrade framework versions
  .dockerignore
  amlb/__init__.py
  amlb/datasets/__init__.py
  amlb/docker.py
  amlb/singularity.py
  examples/custom/extensions/GradientBoosting/__init__.py
  examples/custom/extensions/Stacking/__init__.py
  frameworks/AutoWEKA/__init__.py
  frameworks/DecisionTree/__init__.py
  frameworks/GAMA/__init__.py
  frameworks/H2OAutoML/__init__.py
  frameworks/H2OAutoML/exec.py
  frameworks/H2OAutoML/setup.sh
  frameworks/RandomForest/__init__.py
  frameworks/RandomForest/requirements.txt
  frameworks/TPOT/__init__.py
  frameworks/TPOT/exec.py
  frameworks/TPOT/requirements.txt
  frameworks/TPOT/setup.sh
  frameworks/TunedRandomForest/__init__.py
  frameworks/TunedRandomForest/exec.py
  frameworks/TunedRandomForest/requirements.txt
  frameworks/autosklearn/__init__.py
  frameworks/autosklearn/exec.py
  frameworks/autosklearn/requirements.txt
  frameworks/autosklearn/setup.sh
  frameworks/autoxgboost/__init__.py
  frameworks/constantpredictor/__init__.py
  frameworks/hyperoptsklearn/__init__.py
  frameworks/hyperoptsklearn/exec.py
  frameworks/hyperoptsklearn/requirements.txt
  frameworks/hyperoptsklearn/setup.sh
  frameworks/oboe/__init__.py
  frameworks/oboe/exec.py
  frameworks/oboe/requirements.txt
  frameworks/oboe/setup.sh
  frameworks/ranger/__init__.py
  frameworks/shared/caller.py
  frameworks/shared/requirements.txt
  frameworks/shared/setup.sh
  resources/frameworks.yaml
Labels: framework
