Repository openml/automlbenchmark, pull requests merged in 2020-08, with the labels that each got.

#155 Allow an OpenML suite to define tasks of benchmark
  amlb/aws.py
  amlb/benchmark.py
  amlb/benchmarks/__init__.py
  amlb/benchmarks/file.py
  amlb/benchmarks/openml.py
  amlb/benchmarks/parser.py
  amlb/resources.py
  docs/HOWTO.md
  docs/README.md
  resources/config.yaml
  runbenchmark.py
Labels: enhancement

#161 Reencode truth and predictions to match labels lexicographic order
  amlb/results.py
  docs/HOWTO.md
  docs/README.md
  resources/config.yaml
Labels: bug

#153 Integration of ML-Plan as a default framework
  docs/automl_overview.md
  frameworks/MLPlan/__init__.py
  frameworks/MLPlan/exec.py
  frameworks/MLPlan/requirements.txt
  frameworks/MLPlan/setup.sh
  resources/frameworks.yaml
Labels: framework add
