Repository openml/automlbenchmark, pull requests merged in 2021-08, with the labels that each got.

#374 Clean up framework folders
  .dockerignore
  .gitignore
  amlb/benchmark.py
  amlb/runners/docker.py
  amlb/runners/singularity.py
  frameworks/AutoGluon/setup.sh
  frameworks/AutoWEKA/setup.sh
  frameworks/GAMA/setup.sh
  frameworks/H2OAutoML/setup.sh
  frameworks/MLNet/setup.sh
  frameworks/MLPlan/setup.sh
  frameworks/RandomForest/setup.sh
  frameworks/TPOT/setup.sh
  frameworks/TunedRandomForest/setup.sh
  frameworks/autosklearn/setup.sh
  frameworks/autoxgboost/setup.sh
  frameworks/flaml/setup.sh
  frameworks/lightautoml/setup.sh
  frameworks/mljarsupervised/setup.sh
  frameworks/mlr3automl/setup.sh
  frameworks/ranger/setup.sh
  frameworks/shared/setup.sh
Labels: enhancement

#371 Issue 370: ensure that sparse data are handled by frameworks that don't support them
  amlb/data.py
  amlb/datasets/openml.py
  amlb/frameworks/definitions.py
  amlb/resources.py
  amlb/results.py
  amlb/utils/__init__.py
  amlb/utils/config.py
  amlb/utils/core.py
  amlb/utils/serialization.py
  docs/HOWTO.md
  examples/custom/extensions/GradientBoosting/exec.py
  examples/custom/extensions/Stacking/__init__.py
  examples/custom/extensions/Stacking/exec.py
  frameworks/DecisionTree/exec.py
  frameworks/GAMA/__init__.py
  frameworks/MLPlan/exec.py
  frameworks/TPOT/__init__.py
  frameworks/TPOT/exec.py
  frameworks/autosklearn/__init__.py
  frameworks/constantpredictor/exec.py
  frameworks/flaml/__init__.py
  frameworks/hyperoptsklearn/__init__.py
  frameworks/lightautoml/__init__.py
  frameworks/mljarsupervised/__init__.py
  frameworks/shared/callee.py
  frameworks/shared/caller.py
  frameworks/shared/serialization.py
  frameworks/shared/utils.py
  pytest.ini
  runbenchmark.py
  tests/unit/amlb/utils/serialization/test_serializers.py
Labels: bug, enhancement, framework

#361 Fix LAMA - don't return `truth`
  frameworks/lightautoml/exec.py
Labels: framework

#381 Ensure that framework's extra result columns always appear at the end.
  amlb/results.py
Labels: enhancement

#382 fix usages of compute_score with old signature
  amlb/results.py
  amlb/runners/aws.py
Labels: bug

#383 Improve local logs in AWS mode when many instances in parallel
  amlb/runners/aws.py
Labels: enhancement

#384 Improve readablity of logs in AWS mode
  amlb/runners/aws.py
  amlb/utils/core.py
Labels: enhancement

#387 Fix bug when handling `NoResult` if the remote instance was killed
  amlb/results.py
Labels: bug
