Repository openml/automlbenchmark, pull requests merged in 2023-10, with the labels that each got.

#597 Add contribution guide
  docs/CONTRIBUTING.md
  mkdocs.yml
  requirements-dev.txt
Labels: Documentation

#594 Update Stacking example to work out of the box on Python 3.9
  examples/custom/extensions/Stacking/exec.py
  examples/custom/extensions/Stacking/requirements.txt
  examples/custom/extensions/Stacking/setup.sh
  examples/custom/frameworks.yaml
Labels: bug, Documentation

#600 Fix minor bugs in time series forecasting
  amlb/datasets/file.py
  frameworks/AutoGluon/exec_ts.py
  frameworks/shared/utils.py
  requirements.in
  requirements.txt
  tests/unit/amlb/datasets/file/test_file_dataloader.py
Labels: needs reviewer
